# Generated by Django 5.1.1 on 2024-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
