# Generated by Django 5.1.1 on 2024-09-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0007_alter_transaction_sender_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender_account',
        ),
    ]
